### PR TITLE
Card game was added

### PR DESCRIPTION
**Pull request by tkacholga**

### CODE REVIEW

**Comment by Mikhaela-Paige** [comment]
Would you be able to add in some comments to explain the code?

**Comment by tkacholga** [comment]
> Would you be able to add in some comments to explain the code?

I added them :)

**Comment by Mikhaela-Paige** [comment]
Thank you! It's been merged :)

**Comment by tkacholga** [comment]
> Thank you! It's been merged :)

Thanks! Have a great day!

**Pull request merged**
